# Define boss moving plan
---
leonardo:
  player:
    enter: &enter e
    confirm: &confirm y
    up: &arrow_up w
    down: &arrow_down s
    left: &arrow_left a
    right: &arrow_right d
    tornado: &tornado b
    swirl: &swirl e
    fantasy: &fantasy " "
    bird: &bird v
    c2f: &c2f g
    shield: &shield "1"
  device:
    hunt: hunt-
    move_to_boss_map: boss- 
    frenzy: frenzy-
    move_x: move-
    move_y: updown-
    mine: mine
    break_rune: rune-
    cursor_move: mouseto-
    cursor_click: click-
    arrow: arrow-
    key: key-

inventory:
  shortcut: i
  category:
    max_index_x: 5
    diff_x: 990
    equipment_x: -8908
    equipment_y: -14138
  item:
    max_index_x: 15
    max_index_y: 7
    diff_x: 1434
    diff_y: 2552
    first_x: -8669
    first_y: -12014
    spare_x: -16384
    spare_y: -12014
  
boss:
  - name: zakum
    enabled: true
    index: 2
    commands:
      - move_x_duration: 9.35 # Go into battle map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        arrow_delay: [0.1, 0.1, 0.1, 0.1, 0.1]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 1 # Go to specified position and throw item
        move_y_count: 0
        cursor: null
        throw_item:
          category_index_x: 2
          item_index_x: 0
          item_index_y: 0
          multiple_item: true
        arrow: []
        arrow_delay: []
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Attack
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*fantasy, *tornado, *swirl]
        keyboard_delay: [1, 1, 1]
      - move_x_duration: 3 # Go to find NPC and leave battle map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_right, *enter]
        arrow_delay: [0.3, 0.3, 3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -0.42 # Leave boss map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
  - name: magnus
    enabled: true
    index: 3
    commands:
      - move_x_duration: 2.45 # Go into battle map and attack
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        arrow_delay: [0.3, 0.3, 0.3, 0.3, 0.3, 2]
        keyboard: [*shield, *fantasy, *tornado, *bird]
        keyboard_delay: [1, 1, 1, 1]
      - move_x_duration: 6 # collect treasure
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -6 # leave battle map
        move_y_count: 0
        cursor:
          cursor_x: -26500
          cursor_y: 2000
          click: true
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 0.3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -4.3 # leave boss map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
  - name: hilla
    enabled: true
    index: 4
    commands: null
  - name: pierre
    enabled: true
    index: 8
    commands: null
  - name: vonbon
    enabled: true
    index: 9
    commands: null
  - name: queen
    enabled: true
    index: 10
    commands: null
  - name: vellum
    enabled: true
    index: 11
    commands: null
  - name: vonleon
    enabled: true
    index: 12
    commands: null
  - name: horntail
    enabled: true
    index: 13
    commands: null
  - name: arkarium
    enabled: true
    index: 14
    commands: null
  - name: pinkbean
    enabled: true
    index: 17
    commands: null
...