# Define boss moving plan
---
leonardo:
  player:
    enter: &enter e
    confirm: &confirm y
    up: &arrow_up w
    down: &arrow_down s
    left: &arrow_left a
    right: &arrow_right d
  device:
    hunt: hunt-
    move_to_boss_map: boss- 
    frenzy: frenzy-
    move_x: move-
    move_y: updown-
    mine: mine
    break_rune: rune-
    cursor_move: mouseto-
    cursor_click: click-
    key: key-
    enter: E

inventory:
  shortcut: i
  category:
    max_index_x: 5
    diff_x: 990
    equipment_x: -8908
    equipment_y: -14138
  item:
    max_index_x: 15
    max_index_y: 7
    diff_x: 1434
    diff_y: 2552
    first_x: -8669
    first_y: -12014
    spare_x: -16384
    spare_y: -12014
  
boss:
  - name: zakum
    index: 2
    commands:
      - x_move: 136
        y_move: 0
        throw_item: null
        keyboard: [*arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        delay: [100, 100, 100, 100, 100]
      - x_move: 30
        y_move: 0
        throw_item:
          category_index_x: 2
          item_index_x: 0
          item_index_y: 0
          multiple_item: true
        keyboard: null
        delay: null
      - x_move: -8
        y_move: 0
        throw_item: null
        keyboard: [*arrow_up]
        delay: [100]
  - name: magnus
    index: 3
    commands: null
  - name: hilla
    index: 4
    commands: null
  - name: pierre
    index: 8
    commands: null
  - name: vonbon
    index: 9
    commands: null
  - name: queen
    index: 10
    commands: null
  - name: vellum
    index: 11
    commands: null
  - name: vonleon
    index: 12
    commands: null
  - name: horntail
    index: 13
    commands: null
  - name: arkarium
    index: 14
    commands: null
  - name: pinkbean
    index: 17
    commands: null
...