# Define boss moving plan
---
leonardo:
  player:
    enter: &enter e
    confirm: &confirm y
    up: &arrow_up w
    down: &arrow_down s
    left: &arrow_left a
    right: &arrow_right d
  device:
    hunt: hunt-
    move_to_boss_map: boss- 
    frenzy: frenzy-
    move_x: move-
    move_y: updown-
    mine: mine
    break_rune: rune-
    cursor_move: mouseto-
    cursor_click: click-
    arrow: arrow-
    key: key-

inventory:
  shortcut: i
  category:
    max_index_x: 5
    diff_x: 990
    equipment_x: -8908
    equipment_y: -14138
  item:
    max_index_x: 15
    max_index_y: 7
    diff_x: 1434
    diff_y: 2552
    first_x: -8669
    first_y: -12014
    spare_x: -16384
    spare_y: -12014
  
boss:
  - name: zakum
    index: 2
    commands:
      - move_x_duration: 9.35
        move_y_count: 0
        cursor:
          cursor_x: 0
          cursor_y: 0
          click: true
        throw_item: null
        arrow: [*arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        arrow_delay: [0.1, 0.1, 0.1, 0.1, 0.1]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 2
        move_y_count: 0
        cursor: null
        throw_item:
          category_index_x: 2
          item_index_x: 0
          item_index_y: 0
          multiple_item: true
        arrow: []
        arrow_delay: []
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: []
        keyboard_delay: []
  - name: magnus
    index: 3
    commands: null
  - name: hilla
    index: 4
    commands: null
  - name: pierre
    index: 8
    commands: null
  - name: vonbon
    index: 9
    commands: null
  - name: queen
    index: 10
    commands: null
  - name: vellum
    index: 11
    commands: null
  - name: vonleon
    index: 12
    commands: null
  - name: horntail
    index: 13
    commands: null
  - name: arkarium
    index: 14
    commands: null
  - name: pinkbean
    index: 17
    commands: null
...