# Define boss moving plan
---
leonardo:
  player:
    enter: &enter e
    confirm: &confirm y
    up: &arrow_up w
    down: &arrow_down s
    left: &arrow_left a
    right: &arrow_right d
    jump: &jump f
    attack: &attack ","
    tornado: &tornado b
    swirl: &swirl e
    fantasy: &fantasy " "
    bird: &bird v
    c2f: &c2f g
    wind_move: &wind_move w
    shield: &shield "1"
    creation: &creation S
  device:
    hunt: hunt-
    move_to_boss_map: boss- 
    frenzy: frenzy-
    move_x: move-
    move_y: updown-
    mine: mine
    break_rune: rune-
    cursor_move: mouseto-
    cursor_click: click-
    arrow: arrow-
    key: key-

inventory:
  shortcut: i
  category:
    max_index_x: 5
    diff_x: 990
    equipment_x: -8908
    equipment_y: -14138
  item:
    max_index_x: 15
    max_index_y: 7
    diff_x: 1434
    diff_y: 2552
    first_x: -8669
    first_y: -12014
    spare_x: -16384
    spare_y: -12014
  
boss:
  - name: zakum
    enabled: false
    index: 2
    commands:
      - move_x_duration: 9.35 # Go into battle map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        arrow_delay: [0.3, 0.3, 0.3, 0.3, 0.3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 1 # Go to specified position and throw item then attack
        move_y_count: 0
        cursor: null
        throw_item:
          category_index_x: 2
          item_index_x: 0
          item_index_y: 0
          multiple_item: true
        arrow: []
        arrow_delay: []
        keyboard: [*fantasy, *tornado]
        keyboard_delay: [1, 1]
      - move_x_duration: 3 # Go to find NPC and leave battle map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_right, *enter]
        arrow_delay: [0.3, 0.3, 3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -0.42 # Leave boss map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
  - name: magnus
    enabled: false
    index: 3
    commands:
      - move_x_duration: 2.45 # Go into battle map and attack
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_up, *arrow_up, *arrow_up, *arrow_down, *enter]
        arrow_delay: [0.3, 0.3, 0.3, 0.3, 0.3, 2]
        keyboard: [*shield, *fantasy, *tornado, *bird]
        keyboard_delay: [1, 1, 1, 1]
      - move_x_duration: 6 # collect treasure
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -6 # leave battle map
        move_y_count: 0
        cursor:
          cursor_x: -26500
          cursor_y: 2000
          click: 1
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 0.3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -4.3 # leave boss map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
  - name: hilla
    enabled: false
    index: 4
    commands:
      - move_x_duration: 0 # Go into battle map (deep right)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3, 0.3]
      - move_x_duration: 0 # Go into battle map (cursor to NPC)
        move_y_count: 0
        cursor:
          cursor_x: -3500
          cursor_y: 2000
          click: 1
        throw_item: null
        arrow: [*arrow_up, *enter]
        arrow_delay: [0.3, 0.3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 1 attack and move deep right
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*bird, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
      - move_x_duration: -0.8 # Level 1 (move back and attack)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [0.5]
        keyboard: [*fantasy]
        keyboard_delay: [1]
      - move_x_duration: 0 # Go to Level 2
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 2 attack and move deep right
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*tornado, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
      - move_x_duration: -0.8 # Level 2 (move back and attack)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [0.5]
        keyboard: [*fantasy]
        keyboard_delay: [1]
      - move_x_duration: 0 # Go to Level 3
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 3 attack and collect treasure
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*bird, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3]
      - move_x_duration: -0.3 # Level 3 Go back to original position
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3, 0.3]
      - move_x_duration: 0 # Level 3 Go back to boss map
        move_y_count: 0
        cursor:
          cursor_x: -25500
          cursor_y: -2000
          click: 1
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 2]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: -0.3 # Go back to battle map (deep left)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3]
      - move_x_duration: 0.28 # leave boss map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up]
        arrow_delay: [2]
        keyboard: []
        keyboard_delay: []
  - name: pierre
    enabled: false
    index: 8
    commands:
      - move_x_duration: -1 # Go into boss map Level1
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_up, *enter]
        arrow_delay: [0.3, 0.3, 3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 1 attack and move deep right
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*bird, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
      - move_x_duration: -1.25 # Go to battle map position and use creation
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*creation]
        keyboard_delay: [1]
      - move_x_duration: 0 # Go to battle map, attack and get treasure
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up, *arrow_right, *enter]
        arrow_delay: [0.3, 0.3, 2]
        keyboard: [*fantasy, *attack]
        keyboard_delay: [3, 1]
      - move_x_duration: -0.5 # leave battle map (deep left)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3, 0.3]
      - move_x_duration: 0 # leave battle map (cursor)
        move_y_count: 0
        cursor:
          cursor_x: -30000
          cursor_y: -2000
          click: 1
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 2]
        keyboard: []
        keyboard_delay: []
  - name: vonbon
    enabled: false
    index: 9
    commands:
      - move_x_duration: 1 # Go into boss map Level1
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_up, *enter]
        arrow_delay: [0.3, 0.3, 3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 1 attack and move deep right
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*bird, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *fantasy]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 1]
      - move_x_duration: -0.6 # Go to battle map
        move_y_count: 1
        cursor: null
        throw_item: null
        arrow: [*arrow_up, *arrow_right, *enter]
        arrow_delay: [0.3, 0.3, 2]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # trigger boss, attack and get treasure
        move_y_count: 0
        cursor:
          cursor_x: 1500
          cursor_y: 1500
          click: 1
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*fantasy, *wind_move]
        keyboard_delay: [1, 0.3]
      - move_x_duration: -0.5 # leave battle map (deep left)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3]
      - move_x_duration: 0 # leave battle map (cursor)
        move_y_count: 0
        cursor:
          cursor_x: -30500
          cursor_y: 2500
          click: 1
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 2]
        keyboard: []
        keyboard_delay: []
  - name: queen
    enabled: false
    index: 10
    commands:
      - move_x_duration: -3.5 # Go into boss map Level1
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*confirm, *arrow_up, *enter]
        arrow_delay: [0.3, 0.3, 3]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # Level 1 attack and move deep right
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*bird, *fantasy, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *wind_move, *fantasy]
        keyboard_delay: [1, 1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 1]
      - move_x_duration: -2.4 # Go to battle map
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: [*arrow_up, *arrow_right, *enter]
        arrow_delay: [0.3, 0.3, 2]
        keyboard: []
        keyboard_delay: []
      - move_x_duration: 0 # trigger boss, attack and get treasure
        move_y_count: 0
        cursor:
          cursor_x: 0
          cursor_y: 0
          click: 6
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*fantasy, *attack, *wind_move]
        keyboard_delay: [2, 1, 0.3]
      - move_x_duration: -0.5 # leave battle map (deep left)
        move_y_count: 0
        cursor: null
        throw_item: null
        arrow: []
        arrow_delay: []
        keyboard: [*wind_move, *wind_move, *wind_move]
        keyboard_delay: [0.3, 0.3, 0.3]
      - move_x_duration: 0 # leave battle map (cursor)
        move_y_count: 0
        cursor:
          cursor_x: -30000
          cursor_y: 2000
          click: 1
        throw_item: null
        arrow: [*arrow_right, *enter]
        arrow_delay: [0.3, 2]
        keyboard: []
        keyboard_delay: []
  - name: vellum
    enabled: true
    index: 11
    commands: null
  - name: vonleon
    enabled: true
    index: 12
    commands: null
  - name: horntail
    enabled: true
    index: 13
    commands: null
  - name: arkarium
    enabled: true
    index: 14
    commands: null
  - name: pinkbean
    enabled: true
    index: 17
    commands: null
...